### ISSUE TITLE
Crash while trying to initialize

### ISSUE THREAD

**Issue by spuder** [alister/guard-puppet-lint#6]
When I run guard-puppet-lint, it crashes

Using ruby 2.0.0 with rvm 

```
sowen@Spencers-MacBook-Pro:~/Code/geppetto/puppet-gitlab$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin13.1.0]
```

```
sowen@Spencers-MacBook-Pro:~/Code/geppetto/puppet-gitlab$ gem install guard-puppet-lint
Fetching: guard-puppet-lint-0.2.0.gem (100%)
Successfully installed guard-puppet-lint-0.2.0
1 gem installed
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 16:32:29
sowen@Spencers-MacBook-Pro:~/Code/geppetto/puppet-gitlab$ guard init puppet-lint
/Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/plugin/base.rb:53:in `read': No such file or directory - /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-puppet-lint-0.2.0/lib/guard/puppetlint/templates/Guardfile (Errno::ENOENT)
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/plugin/base.rb:53:in `template'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/plugin_util.rb:129:in `block in add_to_guardfile'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/plugin_util.rb:126:in `open'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/plugin_util.rb:126:in `add_to_guardfile'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/guardfile/generator.rb:62:in `initialize_template'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/guardfile.rb:30:in `initialize_template'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/cli.rb:176:in `block in init'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/cli.rb:175:in `each'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/lib/guard/cli.rb:175:in `init'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/gems/guard-2.6.1/bin/guard:6:in `<top (required)>'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/guard:23:in `load'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/guard:23:in `<main>'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
    from /Users/sowen/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by alister** [comment]
it's been unloved for a while, but I'll take a look over the weekend and try to dupe/fix the issues.

**Comment by spuder** [comment]
Perhaps the reason it is crashing is because it is looking at the wrong directory. 

Guard expects following file: 

```
/Users/sowen/.rvm/gems/ruby-2.1.1/gems/guard-puppet-lint-0.2.0/lib/guard/puppetlint/templates/Guardfile
```

Actual file path (notice it is `puppet-lint` not `puppetlint` 

```
/Users/sowen/.rvm/gems/ruby-2.1.1/gems/guard-puppet-lint-0.2.0/lib/guard/puppet-lint/templates/Guardfile 
```

**Update**

Yes, this is the problem. I proved it by making a symlink 

```
cd /Users/sowen/.rvm/gems/ruby-2.1.1/gems/guard-puppet-lint-0.2.0/lib/guard/
ln -s puppet-lint puppetlint
```

I don't know ruby well enough to solve this. I can't find any hard coded references to 'puppetlint' in the source.
